/* Auto-generated from PSGC on 2025-08-15T08:28:33.577Z */
export const PH_CITIES_BY_PROVINCE = {
  "Abra": [
    "Bangued",
    "Boliney",
    "Bucay",
    "Bucloc",
    "Daguioman",
    "Danglas",
    "Dolores",
    "La Paz",
    "Lacub",
    "Lagangilang",
    "Lagayan",
    "Langiden",
    "Licuan-Baay",
    "Luba",
    "Malibcong",
    "Manabo",
    "Peñarrubia",
    "Pidigan",
    "Pilar",
    "Sallapadan",
    "San Isidro",
    "San Juan",
    "San Quintin",
    "Tayum",
    "Tineg",
    "Tubo",
    "Villaviciosa"
  ],
  "Agusan Del Norte": [
    "Buenavista",
    "Carmen",
    "City of Butuan",
    "City of Cabadbaran",
    "Jabonga",
    "Kitcharao",
    "Las Nieves",
    "Magallanes",
    "Nasipit",
    "Remedios T. Romualdez",
    "Santiago",
    "Tubay"
  ],
  "Agusan Del Sur": [
    "Bunawan",
    "City of Bayugan",
    "Esperanza",
    "La Paz",
    "Loreto",
    "Prosperidad",
    "Rosario",
    "San Francisco",
    "San Luis",
    "Santa Josefa",
    "Sibagat",
    "Talacogon",
    "Trento",
    "Veruela"
  ],
  "Aklan": [
    "Altavas",
    "Balete",
    "Banga",
    "Batan",
    "Buruanga",
    "Ibajay",
    "Kalibo",
    "Lezo",
    "Libacao",
    "Madalag",
    "Makato",
    "Malay",
    "Malinao",
    "Nabas",
    "New Washington",
    "Numancia",
    "Tangalan"
  ],
  "Albay": [
    "Bacacay",
    "Camalig",
    "City of Legazpi",
    "City of Ligao",
    "City of Tabaco",
    "Daraga",
    "Guinobatan",
    "Jovellar",
    "Libon",
    "Malilipot",
    "Malinao",
    "Manito",
    "Oas",
    "Pio Duran",
    "Polangui",
    "Rapu-Rapu",
    "Santo Domingo",
    "Tiwi"
  ],
  "Antique": [
    "Anini-Y",
    "Barbaza",
    "Belison",
    "Bugasong",
    "Caluya",
    "Culasi",
    "Hamtic",
    "Laua-An",
    "Libertad",
    "Pandan",
    "Patnongon",
    "San Jose",
    "San Remigio",
    "Sebaste",
    "Sibalom",
    "Tibiao",
    "Tobias Fornier",
    "Valderrama"
  ],
  "Apayao": [
    "Calanasan",
    "Conner",
    "Flora",
    "Kabugao",
    "Luna",
    "Pudtol",
    "Santa Marcela"
  ],
  "Aurora": [
    "Baler",
    "Casiguran",
    "Dilasag",
    "Dinalungan",
    "Dingalan",
    "Dipaculao",
    "Maria Aurora",
    "San Luis"
  ],
  "Basilan": [
    "Akbar",
    "Al-Barka",
    "City of Lamitan",
    "Hadji Mohammad Ajul",
    "Hadji Muhtamad",
    "Lantawan",
    "Maluso",
    "Sumisip",
    "Tabuan-Lasa",
    "Tipo-Tipo",
    "Tuburan",
    "Ungkaya Pukan"
  ],
  "Bataan": [
    "Abucay",
    "Bagac",
    "City of Balanga",
    "Dinalupihan",
    "Hermosa",
    "Limay",
    "Mariveles",
    "Morong",
    "Orani",
    "Orion",
    "Pilar",
    "Samal"
  ],
  "Batanes": [
    "Basco",
    "Itbayat",
    "Ivana",
    "Mahatao",
    "Sabtang",
    "Uyugan"
  ],
  "Batangas": [
    "Agoncillo",
    "Alitagtag",
    "Balayan",
    "Balete",
    "Batangas City",
    "Bauan",
    "Calaca",
    "Calatagan",
    "City of Lipa",
    "City of Sto. Tomas",
    "City of Tanauan",
    "Cuenca",
    "Ibaan",
    "Laurel",
    "Lemery",
    "Lian",
    "Lobo",
    "Mabini",
    "Malvar",
    "Mataasnakahoy",
    "Nasugbu",
    "Padre Garcia",
    "Rosario",
    "San Jose",
    "San Juan",
    "San Luis",
    "San Nicolas",
    "San Pascual",
    "Santa Teresita",
    "Taal",
    "Talisay",
    "Taysan",
    "Tingloy",
    "Tuy"
  ],
  "Benguet": [
    "Atok",
    "Bakun",
    "Bokod",
    "Buguias",
    "City of Baguio",
    "Itogon",
    "Kabayan",
    "Kapangan",
    "Kibungan",
    "La Trinidad",
    "Mankayan",
    "Sablan",
    "Tuba",
    "Tublay"
  ],
  "Biliran": [
    "Almeria",
    "Biliran",
    "Cabucgayan",
    "Caibiran",
    "Culaba",
    "Kawayan",
    "Maripipi",
    "Naval"
  ],
  "Bohol": [
    "Alburquerque",
    "Alicia",
    "Anda",
    "Antequera",
    "Baclayon",
    "Balilihan",
    "Batuan",
    "Bien Unido",
    "Bilar",
    "Buenavista",
    "Calape",
    "Candijay",
    "Carmen",
    "Catigbian",
    "City of Tagbilaran",
    "Clarin",
    "Corella",
    "Cortes",
    "Dagohoy",
    "Danao",
    "Dauis",
    "Dimiao",
    "Duero",
    "Garcia Hernandez",
    "Getafe",
    "Guindulman",
    "Inabanga",
    "Jagna",
    "Lila",
    "Loay",
    "Loboc",
    "Loon",
    "Mabini",
    "Maribojoc",
    "Panglao",
    "Pilar",
    "President Carlos P. Garcia",
    "Sagbayan",
    "San Isidro",
    "San Miguel",
    "Sevilla",
    "Sierra Bullones",
    "Sikatuna",
    "Talibon",
    "Trinidad",
    "Tubigon",
    "Ubay",
    "Valencia"
  ],
  "Bukidnon": [
    "Baungon",
    "Cabanglasan",
    "City of Malaybalay",
    "City of Valencia",
    "Damulog",
    "Dangcagan",
    "Don Carlos",
    "Impasug-Ong",
    "Kadingilan",
    "Kalilangan",
    "Kibawe",
    "Kitaotao",
    "Lantapan",
    "Libona",
    "Malitbog",
    "Manolo Fortich",
    "Maramag",
    "Pangantucan",
    "Quezon",
    "San Fernando",
    "Sumilao",
    "Talakag"
  ],
  "Bulacan": [
    "Angat",
    "Balagtas",
    "Baliuag",
    "Bocaue",
    "Bulacan",
    "Bustos",
    "Calumpit",
    "City of Malolos",
    "City of Meycauayan",
    "City of San Jose Del Monte",
    "Doña Remedios Trinidad",
    "Guiguinto",
    "Hagonoy",
    "Marilao",
    "Norzagaray",
    "Obando",
    "Pandi",
    "Paombong",
    "Plaridel",
    "Pulilan",
    "San Ildefonso",
    "San Miguel",
    "San Rafael",
    "Santa Maria"
  ],
  "Cagayan": [
    "Abulug",
    "Alcala",
    "Allacapan",
    "Amulung",
    "Aparri",
    "Baggao",
    "Ballesteros",
    "Buguey",
    "Calayan",
    "Camalaniugan",
    "Claveria",
    "Enrile",
    "Gattaran",
    "Gonzaga",
    "Iguig",
    "Lal-Lo",
    "Lasam",
    "Pamplona",
    "Peñablanca",
    "Piat",
    "Rizal",
    "Sanchez-Mira",
    "Santa Ana",
    "Santa Praxedes",
    "Santa Teresita",
    "Santo Niño",
    "Solana",
    "Tuao",
    "Tuguegarao City"
  ],
  "Camarines Norte": [
    "Basud",
    "Capalonga",
    "Daet",
    "Jose Panganiban",
    "Labo",
    "Mercedes",
    "Paracale",
    "San Lorenzo Ruiz",
    "San Vicente",
    "Santa Elena",
    "Talisay",
    "Vinzons"
  ],
  "Camarines Sur": [
    "Baao",
    "Balatan",
    "Bato",
    "Bombon",
    "Buhi",
    "Bula",
    "Cabusao",
    "Calabanga",
    "Camaligan",
    "Canaman",
    "Caramoan",
    "City of Iriga",
    "City of Naga",
    "Del Gallego",
    "Gainza",
    "Garchitorena",
    "Goa",
    "Lagonoy",
    "Libmanan",
    "Lupi",
    "Magarao",
    "Milaor",
    "Minalabac",
    "Nabua",
    "Ocampo",
    "Pamplona",
    "Pasacao",
    "Pili",
    "Presentacion",
    "Ragay",
    "Sagñay",
    "San Fernando",
    "San Jose",
    "Sipocot",
    "Siruma",
    "Tigaon",
    "Tinambac"
  ],
  "Camiguin": [
    "Catarman",
    "Guinsiliban",
    "Mahinog",
    "Mambajao",
    "Sagay"
  ],
  "Capiz": [
    "City of Roxas",
    "Cuartero",
    "Dao",
    "Dumalag",
    "Dumarao",
    "Ivisan",
    "Jamindan",
    "Ma-Ayon",
    "Mambusao",
    "Panay",
    "Panitan",
    "Pilar",
    "Pontevedra",
    "President Roxas",
    "Sapi-An",
    "Sigma",
    "Tapaz"
  ],
  "Catanduanes": [
    "Bagamanoc",
    "Baras",
    "Bato",
    "Caramoran",
    "Gigmoto",
    "Pandan",
    "Panganiban",
    "San Andres",
    "San Miguel",
    "Viga",
    "Virac"
  ],
  "Cavite": [
    "Alfonso",
    "Amadeo",
    "Carmona",
    "City of Bacoor",
    "City of Cavite",
    "City of Dasmariñas",
    "City of General Trias",
    "City of Imus",
    "City of Tagaytay",
    "City of Trece Martires",
    "Gen. Mariano Alvarez",
    "General Emilio Aguinaldo",
    "Indang",
    "Kawit",
    "Magallanes",
    "Maragondon",
    "Mendez",
    "Naic",
    "Noveleta",
    "Rosario",
    "Silang",
    "Tanza",
    "Ternate"
  ],
  "Cebu": [
    "Alcantara",
    "Alcoy",
    "Alegria",
    "Aloguinsan",
    "Argao",
    "Asturias",
    "Badian",
    "Balamban",
    "Bantayan",
    "Barili",
    "Boljoon",
    "Borbon",
    "Carmen",
    "Catmon",
    "City of Bogo",
    "City of Carcar",
    "City of Cebu",
    "City of Lapu-Lapu",
    "City of Mandaue",
    "City of Naga",
    "City of Talisay",
    "City of Toledo",
    "Compostela",
    "Consolacion",
    "Cordova",
    "Daanbantayan",
    "Dalaguete",
    "Danao City",
    "Dumanjug",
    "Ginatilan",
    "Liloan",
    "Madridejos",
    "Malabuyoc",
    "Medellin",
    "Minglanilla",
    "Moalboal",
    "Oslob",
    "Pilar",
    "Pinamungajan",
    "Poro",
    "Ronda",
    "Samboan",
    "San Fernando",
    "San Francisco",
    "San Remigio",
    "Santa Fe",
    "Santander",
    "Sibonga",
    "Sogod",
    "Tabogon",
    "Tabuelan",
    "Tuburan",
    "Tudela"
  ],
  "Cotabato": [
    "Alamada",
    "Aleosan",
    "Antipas",
    "Arakan",
    "Banisilan",
    "Carmen",
    "City of Kidapawan",
    "Kabacan",
    "Libungan",
    "M'lang",
    "Magpet",
    "Makilala",
    "Matalam",
    "Midsayap",
    "Pigkawayan",
    "Pikit",
    "President Roxas",
    "Tulunan"
  ],
  "Davao De Oro": [
    "Compostela",
    "Laak",
    "Mabini",
    "Maco",
    "Maragusan",
    "Mawab",
    "Monkayo",
    "Montevista",
    "Nabunturan",
    "New Bataan",
    "Pantukan"
  ],
  "Davao Del Norte": [
    "Asuncion",
    "Braulio E. Dujali",
    "Carmen",
    "City of Panabo",
    "City of Tagum",
    "Island Garden City of Samal",
    "Kapalong",
    "New Corella",
    "San Isidro",
    "Santo Tomas",
    "Talaingod"
  ],
  "Davao Del Sur": [
    "Bansalan",
    "City of Davao",
    "City of Digos",
    "Hagonoy",
    "Kiblawan",
    "Magsaysay",
    "Malalag",
    "Matanao",
    "Padada",
    "Santa Cruz",
    "Sulop"
  ],
  "Davao Occidental": [
    "Don Marcelino",
    "Jose Abad Santos",
    "Malita",
    "Santa Maria",
    "Sarangani"
  ],
  "Davao Oriental": [
    "Baganga",
    "Banaybanay",
    "Boston",
    "Caraga",
    "Cateel",
    "City of Mati",
    "Governor Generoso",
    "Lupon",
    "Manay",
    "San Isidro",
    "Tarragona"
  ],
  "Dinagat Islands": [
    "Basilisa",
    "Cagdianao",
    "Dinagat",
    "Libjo",
    "Loreto",
    "San Jose",
    "Tubajon"
  ],
  "Eastern Samar": [
    "Arteche",
    "Balangiga",
    "Balangkayan",
    "Can-Avid",
    "City of Borongan",
    "Dolores",
    "General Macarthur",
    "Giporlos",
    "Guiuan",
    "Hernani",
    "Jipapad",
    "Lawaan",
    "Llorente",
    "Maslog",
    "Maydolong",
    "Mercedes",
    "Oras",
    "Quinapondan",
    "Salcedo",
    "San Julian",
    "San Policarpo",
    "Sulat",
    "Taft"
  ],
  "Guimaras": [
    "Buenavista",
    "Jordan",
    "Nueva Valencia",
    "San Lorenzo",
    "Sibunag"
  ],
  "Ifugao": [
    "Aguinaldo",
    "Alfonso Lista",
    "Asipulo",
    "Banaue",
    "Hingyon",
    "Hungduan",
    "Kiangan",
    "Lagawe",
    "Lamut",
    "Mayoyao",
    "Tinoc"
  ],
  "Ilocos Norte": [
    "Adams",
    "Bacarra",
    "Badoc",
    "Bangui",
    "Banna",
    "Burgos",
    "Carasi",
    "City of Batac",
    "City of Laoag",
    "Currimao",
    "Dingras",
    "Dumalneg",
    "Marcos",
    "Nueva Era",
    "Pagudpud",
    "Paoay",
    "Pasuquin",
    "Piddig",
    "Pinili",
    "San Nicolas",
    "Sarrat",
    "Solsona",
    "Vintar"
  ],
  "Ilocos Sur": [
    "Alilem",
    "Banayoyo",
    "Bantay",
    "Burgos",
    "Cabugao",
    "Caoayan",
    "Cervantes",
    "City of Candon",
    "City of Vigan",
    "Galimuyod",
    "Gregorio Del Pilar",
    "Lidlidda",
    "Magsingal",
    "Nagbukel",
    "Narvacan",
    "Quirino",
    "Salcedo",
    "San Emilio",
    "San Esteban",
    "San Ildefonso",
    "San Juan",
    "San Vicente",
    "Santa",
    "Santa Catalina",
    "Santa Cruz",
    "Santa Lucia",
    "Santa Maria",
    "Santiago",
    "Santo Domingo",
    "Sigay",
    "Sinait",
    "Sugpon",
    "Suyo",
    "Tagudin"
  ],
  "Iloilo": [
    "Ajuy",
    "Alimodian",
    "Anilao",
    "Badiangan",
    "Balasan",
    "Banate",
    "Barotac Nuevo",
    "Barotac Viejo",
    "Batad",
    "Bingawan",
    "Cabatuan",
    "Calinog",
    "Carles",
    "City of Iloilo",
    "City of Passi",
    "Concepcion",
    "Dingle",
    "Dueñas",
    "Dumangas",
    "Estancia",
    "Guimbal",
    "Igbaras",
    "Janiuay",
    "Lambunao",
    "Leganes",
    "Lemery",
    "Leon",
    "Maasin",
    "Miagao",
    "Mina",
    "New Lucena",
    "Oton",
    "Pavia",
    "Pototan",
    "San Dionisio",
    "San Enrique",
    "San Joaquin",
    "San Miguel",
    "San Rafael",
    "Santa Barbara",
    "Sara",
    "Tigbauan",
    "Tubungan",
    "Zarraga"
  ],
  "Isabela": [
    "Alicia",
    "Angadanan",
    "Aurora",
    "Benito Soliven",
    "Burgos",
    "Cabagan",
    "Cabatuan",
    "City of Cauayan",
    "City of Ilagan",
    "City of Santiago",
    "Cordon",
    "Delfin Albano",
    "Dinapigue",
    "Divilacan",
    "Echague",
    "Gamu",
    "Jones",
    "Luna",
    "Maconacon",
    "Mallig",
    "Naguilian",
    "Palanan",
    "Quezon",
    "Quirino",
    "Ramon",
    "Reina Mercedes",
    "Roxas",
    "San Agustin",
    "San Guillermo",
    "San Isidro",
    "San Manuel",
    "San Mariano",
    "San Mateo",
    "San Pablo",
    "Santa Maria",
    "Santo Tomas",
    "Tumauini"
  ],
  "Kalinga": [
    "Balbalan",
    "City of Tabuk",
    "Lubuagan",
    "Pasil",
    "Pinukpuk",
    "Rizal",
    "Tanudan",
    "Tinglayan"
  ],
  "La Union": [
    "Agoo",
    "Aringay",
    "Bacnotan",
    "Bagulin",
    "Balaoan",
    "Bangar",
    "Bauang",
    "Burgos",
    "Caba",
    "City of San Fernando",
    "Luna",
    "Naguilian",
    "Pugo",
    "Rosario",
    "San Gabriel",
    "San Juan",
    "Santo Tomas",
    "Santol",
    "Sudipen",
    "Tubao"
  ],
  "Laguna": [
    "Alaminos",
    "Bay",
    "Calauan",
    "Cavinti",
    "City of Biñan",
    "City of Cabuyao",
    "City of Calamba",
    "City of San Pablo",
    "City of San Pedro",
    "City of Santa Rosa",
    "Famy",
    "Kalayaan",
    "Liliw",
    "Los Baños",
    "Luisiana",
    "Lumban",
    "Mabitac",
    "Magdalena",
    "Majayjay",
    "Nagcarlan",
    "Paete",
    "Pagsanjan",
    "Pakil",
    "Pangil",
    "Pila",
    "Rizal",
    "Santa Cruz",
    "Santa Maria",
    "Siniloan",
    "Victoria"
  ],
  "Lanao Del Norte": [
    "Bacolod",
    "Baloi",
    "Baroy",
    "City of Iligan",
    "Kapatagan",
    "Kauswagan",
    "Kolambugan",
    "Lala",
    "Linamon",
    "Magsaysay",
    "Maigo",
    "Matungao",
    "Munai",
    "Nunungan",
    "Pantao Ragat",
    "Pantar",
    "Poona Piagapo",
    "Salvador",
    "Sapad",
    "Sultan Naga Dimaporo",
    "Tagoloan",
    "Tangcal",
    "Tubod"
  ],
  "Lanao Del Sur": [
    "Amai Manabilang",
    "Bacolod-Kalawi",
    "Balabagan",
    "Balindong",
    "Bayang",
    "Binidayan",
    "Buadiposo-Buntong",
    "Bubong",
    "Butig",
    "Calanogas",
    "City of Marawi",
    "Ditsaan-Ramain",
    "Ganassi",
    "Kapai",
    "Kapatagan",
    "Lumba-Bayabao",
    "Lumbaca-Unayan",
    "Lumbatan",
    "Lumbayanague",
    "Madalum",
    "Madamba",
    "Maguing",
    "Malabang",
    "Marantao",
    "Marogong",
    "Masiu",
    "Mulondo",
    "Pagayawan",
    "Piagapo",
    "Picong",
    "Poona Bayabao",
    "Pualas",
    "Saguiaran",
    "Sultan Dumalondong",
    "Tagoloan Ii",
    "Tamparan",
    "Taraka",
    "Tubaran",
    "Tugaya",
    "Wao"
  ],
  "Leyte": [
    "Abuyog",
    "Alangalang",
    "Albuera",
    "Babatngon",
    "Barugo",
    "Bato",
    "Burauen",
    "Calubian",
    "Capoocan",
    "Carigara",
    "City of Baybay",
    "City of Tacloban",
    "Dagami",
    "Dulag",
    "Hilongos",
    "Hindang",
    "Inopacan",
    "Isabel",
    "Jaro",
    "Javier",
    "Julita",
    "Kananga",
    "La Paz",
    "Leyte",
    "Macarthur",
    "Mahaplag",
    "Matag-Ob",
    "Matalom",
    "Mayorga",
    "Merida",
    "Ormoc City",
    "Palo",
    "Palompon",
    "Pastrana",
    "San Isidro",
    "San Miguel",
    "Santa Fe",
    "Tabango",
    "Tabontabon",
    "Tanauan",
    "Tolosa",
    "Tunga",
    "Villaba"
  ],
  "Maguindanao": [
    "Ampatuan",
    "Barira",
    "Buldon",
    "Buluan",
    "Datu Abdullah Sangki",
    "Datu Anggal Midtimbang",
    "Datu Blah T. Sinsuat",
    "Datu Hoffer Ampatuan",
    "Datu Odin Sinsuat",
    "Datu Paglas",
    "Datu Piang",
    "Datu Salibo",
    "Datu Saudi-Ampatuan",
    "Datu Unsay",
    "Gen. s.k. Pendatun",
    "Guindulungan",
    "Kabuntalan",
    "Mamasapano",
    "Mangudadatu",
    "Matanog",
    "Northern Kabuntalan",
    "Pagagawan",
    "Pagalungan",
    "Paglat",
    "Pandag",
    "Parang",
    "Rajah Buayan",
    "Shariff Aguak",
    "Shariff Saydona Mustapha",
    "South Upi",
    "Sultan Kudarat",
    "Sultan Mastura",
    "Sultan Sa Barongis",
    "Talayan",
    "Talitay",
    "Upi"
  ],
  "Marinduque": [
    "Boac",
    "Buenavista",
    "Gasan",
    "Mogpog",
    "Santa Cruz",
    "Torrijos"
  ],
  "Masbate": [
    "Aroroy",
    "Baleno",
    "Balud",
    "Batuan",
    "Cataingan",
    "Cawayan",
    "City of Masbate",
    "Claveria",
    "Dimasalang",
    "Esperanza",
    "Mandaon",
    "Milagros",
    "Mobo",
    "Monreal",
    "Palanas",
    "Pio v. Corpuz",
    "Placer",
    "San Fernando",
    "San Jacinto",
    "San Pascual",
    "Uson"
  ],
  "Misamis Occidental": [
    "Aloran",
    "Baliangao",
    "Bonifacio",
    "Calamba",
    "City of Oroquieta",
    "City of Ozamiz",
    "City of Tangub",
    "Clarin",
    "Concepcion",
    "Don Victoriano Chiongbian",
    "Jimenez",
    "Lopez Jaena",
    "Panaon",
    "Plaridel",
    "Sapang Dalaga",
    "Sinacaban",
    "Tudela"
  ],
  "Misamis Oriental": [
    "Alubijid",
    "Balingasag",
    "Balingoan",
    "Binuangan",
    "City of Cagayan De Oro",
    "City of El Salvador",
    "City of Gingoog",
    "Claveria",
    "Gitagum",
    "Initao",
    "Jasaan",
    "Kinoguitan",
    "Lagonglong",
    "Laguindingan",
    "Libertad",
    "Lugait",
    "Magsaysay",
    "Manticao",
    "Medina",
    "Naawan",
    "Opol",
    "Salay",
    "Sugbongcogon",
    "Tagoloan",
    "Talisayan",
    "Villanueva"
  ],
  "Mountain Province": [
    "Barlig",
    "Bauko",
    "Besao",
    "Bontoc",
    "Natonin",
    "Paracelis",
    "Sabangan",
    "Sadanga",
    "Sagada",
    "Tadian"
  ],

  "NCR":[
    "City of Caloocan",
    "City of Las Piñas",
    "City of Makati",
    "City of Malabon",
    "City of Manila",
    "City of Marikina",
    "City of Muntinlupa",
    "City of Navotas",
    "City of Parañaque",
    "City of Pasay",
    "City of Pasig",
    "City of Quezon",
    "City of San Juan",
    "City of Taguig",
    "City of Valenzuela"
  ],
  
  "Negros Occidental": [
    "Binalbagan",
    "Calatrava",
    "Candoni",
    "Cauayan",
    "City of Bacolod",
    "City of Bago",
    "City of Cadiz",
    "City of Escalante",
    "City of Himamaylan",
    "City of Kabankalan",
    "City of La Carlota",
    "City of Sagay",
    "City of San Carlos",
    "City of Silay",
    "City of Sipalay",
    "City of Talisay",
    "City of Victorias",
    "Enrique B. Magalona",
    "Hinigaran",
    "Hinoba-An",
    "Ilog",
    "Isabela",
    "La Castellana",
    "Manapla",
    "Moises Padilla",
    "Murcia",
    "Pontevedra",
    "Pulupandan",
    "Salvador Benedicto",
    "San Enrique",
    "Toboso",
    "Valladolid"
  ],
  "Negros Oriental": [
    "Amlan",
    "Ayungon",
    "Bacong",
    "Basay",
    "Bindoy",
    "City of Bais",
    "City of Bayawan",
    "City of Canlaon",
    "City of Dumaguete",
    "City of Guihulngan",
    "City of Tanjay",
    "Dauin",
    "Jimalalud",
    "La Libertad",
    "Mabinay",
    "Manjuyod",
    "Pamplona",
    "San Jose",
    "Santa Catalina",
    "Siaton",
    "Sibulan",
    "Tayasan",
    "Valencia",
    "Vallehermoso",
    "Zamboanguita"
  ],
  "Northern Samar": [
    "Allen",
    "Biri",
    "Bobon",
    "Capul",
    "Catarman",
    "Catubig",
    "Gamay",
    "Laoang",
    "Lapinig",
    "Las Navas",
    "Lavezares",
    "Lope De Vega",
    "Mapanas",
    "Mondragon",
    "Palapag",
    "Pambujan",
    "Rosario",
    "San Antonio",
    "San Isidro",
    "San Jose",
    "San Roque",
    "San Vicente",
    "Silvino Lobos",
    "Victoria"
  ],
  "Nueva Ecija": [
    "Aliaga",
    "Bongabon",
    "Cabiao",
    "Carranglan",
    "City of Cabanatuan",
    "City of Gapan",
    "City of Palayan",
    "Cuyapo",
    "Gabaldon",
    "General Mamerto Natividad",
    "General Tinio",
    "Guimba",
    "Jaen",
    "Laur",
    "Licab",
    "Llanera",
    "Lupao",
    "Nampicuan",
    "Pantabangan",
    "Peñaranda",
    "Quezon",
    "Rizal",
    "San Antonio",
    "San Isidro",
    "San Jose City",
    "San Leonardo",
    "Santa Rosa",
    "Santo Domingo",
    "Science City of Muñoz",
    "Talavera",
    "Talugtug",
    "Zaragoza"
  ],
  "Nueva Vizcaya": [
    "Alfonso Castaneda",
    "Ambaguio",
    "Aritao",
    "Bagabag",
    "Bambang",
    "Bayombong",
    "Diadi",
    "Dupax Del Norte",
    "Dupax Del Sur",
    "Kasibu",
    "Kayapa",
    "Quezon",
    "Santa Fe",
    "Solano",
    "Villaverde"
  ],
  "Occidental Mindoro": [
    "Abra De Ilog",
    "Calintaan",
    "Looc",
    "Lubang",
    "Magsaysay",
    "Mamburao",
    "Paluan",
    "Rizal",
    "Sablayan",
    "San Jose",
    "Santa Cruz"
  ],
  "Oriental Mindoro": [
    "Baco",
    "Bansud",
    "Bongabong",
    "Bulalacao",
    "City of Calapan",
    "Gloria",
    "Mansalay",
    "Naujan",
    "Pinamalayan",
    "Pola",
    "Puerto Galera",
    "Roxas",
    "San Teodoro",
    "Socorro",
    "Victoria"
  ],
  "Palawan": [
    "Aborlan",
    "Agutaya",
    "Araceli",
    "Balabac",
    "Bataraza",
    "Brooke's Point",
    "Busuanga",
    "Cagayancillo",
    "City of Puerto Princesa",
    "Coron",
    "Culion",
    "Cuyo",
    "Dumaran",
    "El Nido",
    "Kalayaan",
    "Linapacan",
    "Magsaysay",
    "Narra",
    "Quezon",
    "Rizal",
    "Roxas",
    "San Vicente",
    "Sofronio Española",
    "Taytay"
  ],
  "Pampanga": [
    "Apalit",
    "Arayat",
    "Bacolor",
    "Candaba",
    "City of Angeles",
    "City of San Fernando",
    "Floridablanca",
    "Guagua",
    "Lubao",
    "Mabalacat City",
    "Macabebe",
    "Magalang",
    "Masantol",
    "Mexico",
    "Minalin",
    "Porac",
    "San Luis",
    "San Simon",
    "Santa Ana",
    "Santa Rita",
    "Sasmuan",
    "Sto. Tomas"
  ],
  "Pangasinan": [
    "Agno",
    "Aguilar",
    "Alcala",
    "Anda",
    "Asingan",
    "Balungao",
    "Bani",
    "Basista",
    "Bautista",
    "Bayambang",
    "Binalonan",
    "Binmaley",
    "Bolinao",
    "Bugallon",
    "Burgos",
    "Calasiao",
    "City of Alaminos",
    "City of Dagupan",
    "City of San Carlos",
    "City of Urdaneta",
    "Dasol",
    "Infanta",
    "Labrador",
    "Laoac",
    "Lingayen",
    "Mabini",
    "Malasiqui",
    "Manaoag",
    "Mangaldan",
    "Mangatarem",
    "Mapandan",
    "Natividad",
    "Pozorrubio",
    "Rosales",
    "San Fabian",
    "San Jacinto",
    "San Manuel",
    "San Nicolas",
    "San Quintin",
    "Santa Barbara",
    "Santa Maria",
    "Santo Tomas",
    "Sison",
    "Sual",
    "Tayug",
    "Umingan",
    "Urbiztondo",
    "Villasis"
  ],
  "Quezon": [
    "Agdangan",
    "Alabat",
    "Atimonan",
    "Buenavista",
    "Burdeos",
    "Calauag",
    "Candelaria",
    "Catanauan",
    "City of Lucena",
    "City of Tayabas",
    "Dolores",
    "General Luna",
    "General Nakar",
    "Guinayangan",
    "Gumaca",
    "Infanta",
    "Jomalig",
    "Lopez",
    "Lucban",
    "Macalelon",
    "Mauban",
    "Mulanay",
    "Padre Burgos",
    "Pagbilao",
    "Panukulan",
    "Patnanungan",
    "Perez",
    "Pitogo",
    "Plaridel",
    "Polillo",
    "Quezon",
    "Real",
    "Sampaloc",
    "San Andres",
    "San Antonio",
    "San Francisco",
    "San Narciso",
    "Sariaya",
    "Tagkawayan",
    "Tiaong",
    "Unisan"
  ],
  "Quirino": [
    "Aglipay",
    "Cabarroguis",
    "Diffun",
    "Maddela",
    "Nagtipunan",
    "Saguday"
  ],
  "Rizal": [
    "Angono",
    "Baras",
    "Binangonan",
    "Cainta",
    "Cardona",
    "City of Antipolo",
    "Jala-Jala",
    "Morong",
    "Pililla",
    "Rodriguez",
    "San Mateo",
    "Tanay",
    "Taytay",
    "Teresa"
  ],
  "Romblon": [
    "Alcantara",
    "Banton",
    "Cajidiocan",
    "Calatrava",
    "Concepcion",
    "Corcuera",
    "Ferrol",
    "Looc",
    "Magdiwang",
    "Odiongan",
    "Romblon",
    "San Agustin",
    "San Andres",
    "San Fernando",
    "San Jose",
    "Santa Fe",
    "Santa Maria"
  ],
  "Samar": [
    "Almagro",
    "Basey",
    "Calbiga",
    "City of Calbayog",
    "City of Catbalogan",
    "Daram",
    "Gandara",
    "Hinabangan",
    "Jiabong",
    "Marabut",
    "Matuguinao",
    "Motiong",
    "Pagsanghan",
    "Paranas",
    "Pinabacdao",
    "San Jorge",
    "San Jose De Buan",
    "San Sebastian",
    "Santa Margarita",
    "Santa Rita",
    "Santo Niño",
    "Tagapul-An",
    "Talalora",
    "Tarangnan",
    "Villareal",
    "Zumarraga"
  ],
  "Sarangani": [
    "Alabel",
    "Glan",
    "Kiamba",
    "Maasim",
    "Maitum",
    "Malapatan",
    "Malungon"
  ],
  "Siquijor": [
    "Enrique Villanueva",
    "Larena",
    "Lazi",
    "Maria",
    "San Juan",
    "Siquijor"
  ],
  "Sorsogon": [
    "Barcelona",
    "Bulan",
    "Bulusan",
    "Casiguran",
    "Castilla",
    "City of Sorsogon",
    "Donsol",
    "Gubat",
    "Irosin",
    "Juban",
    "Magallanes",
    "Matnog",
    "Pilar",
    "Prieto Diaz",
    "Santa Magdalena"
  ],
  "South Cotabato": [
    "Banga",
    "City of General Santos",
    "City of Koronadal",
    "Lake Sebu",
    "Norala",
    "Polomolok",
    "Santo Niño",
    "Surallah",
    "T'boli",
    "Tampakan",
    "Tantangan",
    "Tupi"
  ],
  "Southern Leyte": [
    "Anahawan",
    "Bontoc",
    "City of Maasin",
    "Hinunangan",
    "Hinundayan",
    "Libagon",
    "Liloan",
    "Limasawa",
    "Macrohon",
    "Malitbog",
    "Padre Burgos",
    "Pintuyan",
    "Saint Bernard",
    "San Francisco",
    "San Juan",
    "San Ricardo",
    "Silago",
    "Sogod",
    "Tomas Oppus"
  ],
  "Sultan Kudarat": [
    "Bagumbayan",
    "City of Tacurong",
    "Columbio",
    "Esperanza",
    "Isulan",
    "Kalamansig",
    "Lambayong",
    "Lebak",
    "Lutayan",
    "Palimbang",
    "President Quirino",
    "Sen. Ninoy Aquino"
  ],
  "Sulu": [
    "Hadji Panglima Tahil",
    "Indanan",
    "Jolo",
    "Kalingalan Caluang",
    "Lugus",
    "Luuk",
    "Maimbung",
    "Old Panamao",
    "Omar",
    "Pandami",
    "Panglima Estino",
    "Pangutaran",
    "Parang",
    "Pata",
    "Patikul",
    "Siasi",
    "Talipao",
    "Tapul",
    "Tongkil"
  ],
  "Surigao Del Norte": [
    "Alegria",
    "Bacuag",
    "Burgos",
    "City of Surigao",
    "Claver",
    "Dapa",
    "Del Carmen",
    "General Luna",
    "Gigaquit",
    "Mainit",
    "Malimono",
    "Pilar",
    "Placer",
    "San Benito",
    "San Francisco",
    "San Isidro",
    "Santa Monica",
    "Sison",
    "Socorro",
    "Tagana-An",
    "Tubod"
  ],
  "Surigao Del Sur": [
    "Barobo",
    "Bayabas",
    "Cagwait",
    "Cantilan",
    "Carmen",
    "Carrascal",
    "City of Bislig",
    "City of Tandag",
    "Cortes",
    "Hinatuan",
    "Lanuza",
    "Lianga",
    "Lingig",
    "Madrid",
    "Marihatag",
    "San Agustin",
    "San Miguel",
    "Tagbina",
    "Tago"
  ],
  "Tarlac": [
    "Anao",
    "Bamban",
    "Camiling",
    "Capas",
    "City of Tarlac",
    "Concepcion",
    "Gerona",
    "La Paz",
    "Mayantoc",
    "Moncada",
    "Paniqui",
    "Pura",
    "Ramos",
    "San Clemente",
    "San Jose",
    "San Manuel",
    "Santa Ignacia",
    "Victoria"
  ],
  "Tawi-Tawi": [
    "Bongao",
    "Languyan",
    "Mapun",
    "Panglima Sugala",
    "Sapa-Sapa",
    "Sibutu",
    "Simunul",
    "Sitangkai",
    "South Ubian",
    "Tandubas",
    "Turtle Islands"
  ],
  "Zambales": [
    "Botolan",
    "Cabangan",
    "Candelaria",
    "Castillejos",
    "City of Olongapo",
    "Iba",
    "Masinloc",
    "Palauig",
    "San Antonio",
    "San Felipe",
    "San Marcelino",
    "San Narciso",
    "Santa Cruz",
    "Subic"
  ],
  "Zamboanga Del Norte": [
    "Bacungan",
    "Baliguian",
    "City of Dapitan",
    "City of Dipolog",
    "Godod",
    "Gutalac",
    "Jose Dalman",
    "Kalawit",
    "Katipunan",
    "La Libertad",
    "Labason",
    "Liloy",
    "Manukan",
    "Mutia",
    "Piñan",
    "Polanco",
    "Pres. Manuel a. Roxas",
    "Rizal",
    "Salug",
    "Sergio osmeña Sr.",
    "Siayan",
    "Sibuco",
    "Sibutad",
    "Sindangan",
    "Siocon",
    "Sirawai",
    "Tampilisan"
  ],
  "Zamboanga Del Sur": [
    "Aurora",
    "Bayog",
    "City of Pagadian",
    "City of Zamboanga",
    "Dimataling",
    "Dinas",
    "Dumalinao",
    "Dumingag",
    "Guipos",
    "Josefina",
    "Kumalarang",
    "Labangan",
    "Lakewood",
    "Lapuyan",
    "Mahayag",
    "Margosatubig",
    "Midsalip",
    "Molave",
    "Pitogo",
    "Ramon Magsaysay",
    "San Miguel",
    "San Pablo",
    "Sominot",
    "Tabina",
    "Tambulig",
    "Tigbao",
    "Tukuran",
    "Vincenzo a. Sagun"
  ],
  "Zamboanga Sibugay": [
    "Alicia",
    "Buug",
    "Diplahan",
    "Imelda",
    "Ipil",
    "Kabasalan",
    "Mabuhay",
    "Malangas",
    "Naga",
    "Olutanga",
    "Payao",
    "Roseller Lim",
    "Siay",
    "Talusan",
    "Titay",
    "Tungawan"
  ]
};
export default PH_CITIES_BY_PROVINCE;
